version: '3.8'

services:
  london_parser:
    build:
      context: .
    entrypoint: ["/app/entrypoint_london.sh"]
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mongo
    environment:
      - SCRIPT_PATH=/app/London/main.py
      - DATABASE_URL=postgresql+asyncpg://serp_admin:mr_svenson_6612@postgres:5432/serp_parsers

  netherlands_parser:
    build:
      context: .
    entrypoint: ["/app/entrypoint_netherlands.sh"]
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mongo
    environment:
      - SCRIPT_PATH=/app/Netherlands/main.py
      - DATABASE_URL=postgresql+asyncpg://serp_admin:mr_svenson_6612@postgres:5432/serp_parsers


  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=serp_admin
      - POSTGRES_PASSWORD=mr_svenson_6612
      - POSTGRES_DB=serp_parsers
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  db_init:
    build:
      context: .
    entrypoint: [ "/app/entrypoint_db.sh" ]
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+asyncpg://serp_admin:mr_svenson_6612@postgres:5432/serp_parsers

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
